"""add unit_price in order_product_association

Revision ID: 74abc95927a9
Revises: 08646b64afa8
Create Date: 2025-08-13 13:14:45.807146

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "74abc95927a9"
down_revision: Union[str, Sequence[str], None] = "08646b64afa8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order_product_association", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("unit_price", sa.Integer(), server_default="0", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order_product_association", schema=None) as batch_op:
        batch_op.drop_column("unit_price")

    # ### end Alembic commands ###
