"""add count column to order product association table

Revision ID: 08646b64afa8
Revises: 94baa87b9131
Create Date: 2025-08-13 12:30:00.906969

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "08646b64afa8"
down_revision: Union[str, Sequence[str], None] = "94baa87b9131"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order_product_association", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("count", sa.Integer(), server_default="1", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order_product_association", schema=None) as batch_op:
        batch_op.drop_column("count")

    # ### end Alembic commands ###
