"""fixed order product association

Revision ID: 94baa87b9131
Revises: bddee70390d4
Create Date: 2025-08-13 12:11:38.861718

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "94baa87b9131"
down_revision: Union[str, Sequence[str], None] = "bddee70390d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order_product_association", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("index_unique_order_product"), type_="unique"
        )
        batch_op.create_unique_constraint(
            "idx_unique_order_product", ["order_id", "product_id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order_product_association", schema=None) as batch_op:
        batch_op.drop_constraint("idx_unique_order_product", type_="unique")
        batch_op.create_unique_constraint(
            batch_op.f("index_unique_order_product"), ["order_id", "product_id"]
        )

    # ### end Alembic commands ###
